-- ============================================================
-- Election 2025 Schema Setup
-- Run with Supabase CLI or psql
-- ============================================================

begin;

-- Drop existing tables if you intend to recreate them manually
-- (uncomment when you are ready)
-- drop table if exists public.voters cascade;
-- drop table if exists public.locations cascade;

create table if not exists public.locations (
    location_id bigint generated by default as identity primary key,
    location_number text not null,
    location_name text not null,
    location_address text not null,
    governorate text not null,
    district text not null,
    main_committee_id text null,
    police_department text null,
    total_voters integer not null default 0,
    created_at timestamp with time zone not null default now()
) tablespace pg_default;

create index if not exists idx_locations_number
    on public.locations using btree (location_number) tablespace pg_default;

create table if not exists public.voters (
  id bigserial not null,
  voter_id integer not null,
  full_name text not null,
  location_id bigint not null,
  source_page integer null,
  created_at timestamp with time zone null default now(),
  constraint voters_pkey primary key (id),
  constraint fk_voters_location foreign key (location_id)
      references public.locations (location_id) on delete cascade
) tablespace pg_default;

create index if not exists idx_voters_location_id
    on public.voters using btree (location_id) tablespace pg_default;

create index if not exists idx_voters_full_name
    on public.voters using gin (to_tsvector('arabic'::regconfig, full_name))
    tablespace pg_default;

commit;

-- ============================================================
-- Verification Queries
-- ============================================================
-- Verify table existence
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in ('locations', 'voters');

-- Check foreign-key integrity helper (no rows = all good)
select v.id, v.location_id
from public.voters v
left join public.locations l on l.location_id = v.location_id
where l.location_id is null
limit 10;
